# Generated by Django 5.2.4 on 2025-07-11 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings_app', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='deposit_amount',
            field=models.PositiveIntegerField(default=500),
            preserve_default=False,
        ),
    ]
